### ISSUE TITLE
comparison of t and p values paper

### ISSUE THREAD

**Issue by lisallreiber** [aaronpeikert/repro-COMP2PSYCH#18]
Could you provide the Link to the paper/project which checks automatically whether t and p values in papers match ?

Merci 🐣

**Comment by aaronpeikert** [comment]
The project (and R package) is [statcheck](https://github.com/MicheleNuijten/statcheck). The paper I referred to is:

Nuijten, Michèle B.; Hartgerink, Chris H. J.; van Assen, Marcel A. L. M.; Epskamp, Sacha; Wicherts, Jelte M. (2015-10-23). "The prevalence of statistical reporting errors in psychology (1985–2013)". Behavior Research Methods. 48 (4): 1205–1226. doi:10.3758/s13428-015-0664-2. ISSN 1554-3528. PMC 5101263. PMID 26497820.
